# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-22 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
