# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-24 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_auto_20190424_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='publishers',
            field=models.ManyToManyField(to='index.Publisher'),
        ),
    ]
