# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 07:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.IntegerField(choices=[(0, 'ICBC'), (1, 'CBC'), (2, 'BC'), (3, 'ABC'), (4, 'CCB'), (5, 'Alipay')], default=0, verbose_name='银行')),
                ('bankNo', models.CharField(max_length=50, null=True, verbose_name='银行卡号')),
                ('bankpwd', models.CharField(max_length=200, null=True, verbose_name='交易密码')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
