# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='desc',
            field=models.CharField(default='wu', max_length=200, verbose_name='描述'),
        ),
    ]
