# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-07 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_courseorg_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='category',
            field=models.CharField(choices=[('pxjg', '培训机构'), ('gx', '高校'), ('gr', '个人')], default='培训机构', max_length=20, verbose_name='机构类别'),
        ),
    ]
