# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 14:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20190508_1020'),
        ('organization', '0003_auto_20190508_1437'),
    ]

    operations = [
    ]
