# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-05-08 17:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=1, upload_to='teacher/%Y/%m', verbose_name='头像'),
            preserve_default=False,
        ),
    ]
