# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-04 01:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_carinfo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('ordertime', models.DateTimeField(auto_now_add=True, verbose_name='成交时间')),
                ('orderStatus', models.IntegerField(choices=[(0, '未支付'), (1, '已支付'), (2, '交易成功'), (3, '交易失败')], default=0, verbose_name='订单状态')),
                ('isDelete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('buser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to=settings.AUTH_USER_MODEL)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sale.CarInfo', verbose_name='车辆信息')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '订单',
                'verbose_name_plural': '订单',
            },
        ),
    ]
