# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale', '0002_carinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格')),
                ('mileage', models.IntegerField(verbose_name='公里数')),
                ('carDetail', models.TextField(verbose_name='车辆信息')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.CarInfo')),
                ('suser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': '购买意愿表',
                'verbose_name': '购买意愿表',
            },
        ),
    ]
