# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-07-03 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('btitle', models.CharField(max_length=50, null=True, verbose_name='品牌名称')),
                ('logo_brand', models.ImageField(default='normal.png', upload_to='img/car', verbose_name='车标')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '品牌表',
                'verbose_name_plural': '品牌表',
            },
        ),
    ]
